---

## Lab 3 Exercises

Student Name: 任子桐，司浩言，余承恩

Student ID: 3240104990，3230105125，3240100479

Date: 2026/3/16

### E1. State Transformation

Now consider a generic quantum state on the Bloch sphere

$$ \left \vert \psi \right \rangle = \alpha \left \vert 0 \right \rangle + \beta \left \vert 1 \right \rangle = \left ( 
    \begin{array}{c}
    \alpha \\
    \beta
    \end{array} 
    \right ), \quad \alpha, \beta \in \mathbb{C}$$ 

normalized by (the probabilistic interpretation)

$$ \langle \psi \vert \psi \rangle = |\alpha|^2 + |\beta|^2 = 1. $$

We can alternatively write down the state in the $\sigma_x$ basis, 

$$ \left \vert + \right \rangle = \frac1{\sqrt2} \left ( 
    \begin{array}{c}
    1 \\
    1
    \end{array} 
    \right ), \ 
   \left \vert - \right \rangle = \frac1{\sqrt2} \left ( 
    \begin{array}{c}
    1 \\
    -1
    \end{array} 
    \right ).
$$

Assume the state is 

$$ \left \vert \psi \right \rangle = \alpha' \left \vert + \right \rangle + \beta' \left \vert - \right \rangle, 
\quad \alpha, \beta \in \mathbb{C} 
$$ 

What matrix transforms $(\alpha, \beta)$ to $(\alpha', \beta')$? What are the matrix representations for $\sigma_x$, $\sigma_y$, $\sigma_z$ in the new basis? Compare the the numpy realization with the derivation using the Dirac notation.

In [1]:
from qutip import Qobj
import numpy as np

# Pauli matrices in {|0>, |1>}
sx = Qobj([[0, 1],
           [1, 0]])

sy = Qobj([[0, -1j],
           [1j, 0]])

sz = Qobj([[1, 0],
           [0, -1]])

# Change-of-basis matrix: columns are |+> and |->
S = Qobj((1/np.sqrt(2)) * np.array([[1, 1],
                                    [1, -1]], dtype=complex))

print("Transformation matrix from (alpha', beta') in {|+>, |->} to (alpha, beta) in {|0>, |1>}:")
print(S.full())

print("\nTransformation matrix from (alpha, beta) to (alpha', beta'):")
print(S.inv().full())

# A' = S^\dagger A S
sx_new = S.dag() * sx * S
sy_new = S.dag() * sy * S
sz_new = S.dag() * sz * S

print("\nsigma_x in {|+>, |->} basis:")
print(np.real_if_close(np.round(sx_new.full(), 10)))

print("\nsigma_y in {|+>, |->} basis:")
print(np.real_if_close(np.round(sy_new.full(), 10)))

print("\nsigma_z in {|+>, |->} basis:")
print(np.real_if_close(np.round(sz_new.full(), 10)))

Transformation matrix from (alpha', beta') in {|+>, |->} to (alpha, beta) in {|0>, |1>}:
[[ 0.70710678+0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678+0.j]]

Transformation matrix from (alpha, beta) to (alpha', beta'):
[[ 0.70710678-0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678-0.j]]

sigma_x in {|+>, |->} basis:
[[ 1. -0.]
 [ 0. -1.]]

sigma_y in {|+>, |->} basis:
[[0.-0.j 0.+1.j]
 [0.-1.j 0.+0.j]]

sigma_z in {|+>, |->} basis:
[[-0.  1.]
 [ 1. -0.]]


### E2. Two Qubits

We will discuss how to describe states and measurements in multi-qubit systems in the coming lecture. Let us do some warm-up exercises here. Assume we use four column vectors 

$$ \vert 00 \rangle = \left ( \begin{array}{c} 1 \\ 0 
\\ 0 \\ 0 \end{array} \right ), \ 
   \vert 01 \rangle = \left ( \begin{array}{c} 0 \\ 1 
\\ 0 \\ 0 \end{array} \right ), \ 
   \vert 10 \rangle = \left ( \begin{array}{c} 0 \\ 0 
\\ 1 \\ 0 \end{array} \right ), \ 
   \vert 11 \rangle = \left ( \begin{array}{c} 0 \\ 0 
\\ 0 \\ 1 \end{array} \right ). \ 
$$

to represent two-bit states.
Construct $\sigma_{1x}$, $\sigma_{1y}$, $\sigma_{1z}$, now $4 \times 4$ matrices, that operates only on the first qubit. Likewise, construct $\sigma_{2x}$, $\sigma_{2y}$, $\sigma_{2z}$ that operates only on the second qubit. 

Use your result to calculate 

$$ \vec \sigma_1 \cdot \vec \sigma_2 = \sigma_{1x} \sigma_{2x} + \sigma_{1y} \sigma_{2y} + \sigma_{1z} \sigma_{2z}. $$

Diagonalize $\vec \sigma_1 \cdot \vec \sigma_2$ and list the four eigenvectors and their corresponding eigenvalues. 

In [2]:
from qutip import qeye, tensor, sigmax, sigmay, sigmaz
import numpy as np

I = qeye(2)

# Operators on qubit 1
s1x = tensor(sigmax(), I)
s1y = tensor(sigmay(), I)
s1z = tensor(sigmaz(), I)

# Operators on qubit 2
s2x = tensor(I, sigmax())
s2y = tensor(I, sigmay())
s2z = tensor(I, sigmaz())

print("sigma_1x =")
print(np.real_if_close(np.round(s1x.full(), 10)))

print("\nsigma_1y =")
print(np.real_if_close(np.round(s1y.full(), 10)))

print("\nsigma_1z =")
print(np.real_if_close(np.round(s1z.full(), 10)))

print("\nsigma_2x =")
print(np.real_if_close(np.round(s2x.full(), 10)))

print("\nsigma_2y =")
print(np.real_if_close(np.round(s2y.full(), 10)))

print("\nsigma_2z =")
print(np.real_if_close(np.round(s2z.full(), 10)))

sigma_dot = s1x * s2x + s1y * s2y + s1z * s2z

print("\nsigma_1 · sigma_2 =")
print(np.real_if_close(np.round(sigma_dot.full(), 10)))

eigvals, eigvecs = sigma_dot.eigenstates()

print("\nEigenvalues:")
print(np.real_if_close(np.round(np.array(eigvals), 10)))

print("\nEigenvectors:")
for i, vec in enumerate(eigvecs):
    print(f"\nEigenvector {i}:")
    print(np.real_if_close(np.round(vec.full(), 10)))

sigma_1x =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

sigma_1y =
[[0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]]

sigma_1z =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]

sigma_2x =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

sigma_2y =
[[0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]]

sigma_2z =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

sigma_1 · sigma_2 =
[[ 1.  0.  0.  0.]
 [ 0. -1.  2.  0.]
 [ 0.  2. -1.  0.]
 [ 0.  0.  0.  1.]]

Eigenvalues:
[-3.  1.  1.  1.]

Eigenvectors:

Eigenvector 0:
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]

Eigenvector 1:
[[1.]
 [0.]
 [0.]
 [0.]]

Eigenvector 2:
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]

Eigenvector 3:
[[0.]
 [0.]
 [0.]
 [1.]]
